github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: mkljczk
open_collective: # Replace with a single Open Collective username
ko_fi: mkljczk
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: mkljczk
issuehunt: m4sk1n
otechie: # Replace with a single Otechie username
custom: # Replace with a single custom sponsorship URL
